title: Rodel Manalo Talampas
user_title: Solutions Architect | Designer | Developer
description: Personal site, articles, and resume for Rodel Manalo Talampas.
url: "https://rodel.talampas.net"
baseurl: ""

theme_skin: blue # blue turquoise green berry orange ceramic
chrome_mobile_color:

facebook: rodel.talampas
instagram: limacon
linkedin: rodel-talampas-ba418732
github:  rodel-talampas
email: rodel.talampas@gmail.com

# images
bimage_small: rodel_small.png
bimage_medium: rodel_medium.png
bimage_large: rodel_large.png
port_bimage_small: rodel_small_portrait.png
port_bimage_medium: rodel_medium_portrait.png
port_bimage_large: rodel_large_portrait.png


# Build settings
theme: minima
plugins:
  - jekyll-feed

exclude:
  - vendor/
  - README.md
