# Site settings
theme: jekyll-theme-minimal

title: "Rodel's Resume"
description: "A Resume created using Jekyll Template provided by #joelglovier."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

name                     : "Your Name"
description              : "An amazing website."

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Rodel M. Talampas"
resume_title:                   "Experienced Software Solutions Designer, Architect and Developer"
resume_contact_email:           "rodel.talampas@gmail.com"
resume_contact_telephone:       "555-7334"
resume_contact_address:         "742 Evergreen Terrace, Springfield"
resume_header_contact_info: "742 Evergreen Terrace, Springfield | 555-7334 | rodel.talampas@gmail.com"
resume_header_intro: "<p><ul><li>IT Professional with 19 years of total working experience</li></ul></p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_summary:         true
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/rodel-talampas"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/rodel-talampas-ba418732"
  resume_instagram_url:         "https://www.instagram.com/limacon/"
  #resume_website_url:           "http://joelglovier.com"
  resume_twitter_url:           "https://twitter.com/lim9con"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
